codecov:
  require_ci_to_pass: true
  notify:
    after_n_builds: 1

coverage:
  precision: 2
  round: nearest
  range: 60..90
  status:
    project:
      default:
        target: auto
        threshold: 1%
        if_not_found: success
    patch:
      default:
        target: auto
        threshold: 1%
        if_not_found: success

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false

ignore:
  - "build/**"
  - "install/**"
  - "**/_deps/**"
  - "**/third_party/**"
  - "cpp/test/**"
  - "lite/test/**"
